config/routes.rb
Rails.application.routes.draw do
  #get 'top/index'
  get 'users/index'
  get 'use/' => "term#use"
  get 'service/' => "term#service"
  get 'search/' => "search#index"

  root "posts#index"
  resources :comments
  resources :walls
  resources :posts
  resources :blacklists
  #resources :top
  resources :term

  match '/users',   to: 'users#index',   via: 'get'
  match '/users/show/:id',   to: 'users#show',   via: 'get'
  match '/users/edit/:id',   to: 'users#edit',   via: 'get'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :posts do
    resources :likes
  end
  resources :posts do
    resources :downvotes
  end
  resources :posts do
    resources :inappropriates
  end


  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blacklist.rb
class Blacklist < ApplicationRecord
    has_one :user
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_one_attached :image
end

app/models/downvote.rb
class Downvote < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/inappropriate.rb
class Inappropriate < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comment
  has_many_attached :image
  has_many :likes, dependent: :destroy
  has_many :downvotes, dependent: :destroy
  has_many :inappropriates, dependent: :destroy
  has_one_attached :image

  def self.search(search)
    if search
      where(["title LIKE ?","%#{search}%"])
    else
      all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  devise :omniauthable, omniauth_providers: [:google_oauth2]
  has_many :post
  has_many :comment
  belongs_to :blacklist, optional: true
  has_one_attached :avatar
  


  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first

    # Uncomment the section below if you want users to be created if they don't exist
    unless user
      user = User.create(name: data['first_name'],
         lastname: data['last_name'],
         email: data['email'],
         password: Devise.friendly_token[0,20]
      )
    end
    user
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:text, :link, :picture, :user_id, :post_id, :image)
    end
end

app/controllers/term_controller.rb
class TermController < ApplicationController
  def use
  end

  def service
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def title(page_title)
        content_for(:title) { page_title }
      end
end

app/helpers/blacklists_helper.rb
module BlacklistsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
      count: resource.errors.count,
      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">x</button>
      <h4>#{sentence}</h4>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/downvotes_helper.rb
module DownvotesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/term_helper.rb
module TermHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/helpers/walls_helper.rb
module WallsHelper
end

app/views/comments/_form.html.erb
<style media="screen">
  input[type=text], select {
  width: 100%;
  padding: 12px 30px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
  }

  textarea {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
  }

  input[type=submit] {
  width: 100%;
  margin-top: 0%;
  width: fit-content ;
  position: relative;
  border-color: #ff4900!important;
  background-color: #ffd9b3!important;
  color: #ff4900!important;
  }



</style>

<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container">
    <div class="row">

    <div class="col-ml-6">


      <%= form.text_area :text, rows:"5", :placeholder  => "Text" %>
      <div class="form-group" align="center">
      <%= image_tag(@comment.image, style:'width:200px')  if @comment.image.attached?%>
      </div>

        <div class="field">
              <%= form.hidden_field :user_id, value: current_user.id %>
              <% if @comment.post_id %>
              <%= form.hidden_field :post_id, value: @comment.post_id %>
              <%else%>
              <%= form.hidden_field :post_id, value: "#{params[:post_id]}" %>
              <%end%>
            </div>



        <div class="actions">
          <%= form.submit "Submit", class: "btn btn-primary" %>
          <a  class="btn btn-primary" href="/posts/<%= @post %>">Cancel</a>
        </div>

            <h3> Add File</h3>
            <%= form.file_field :image, direct_upload: true %>
        </div>

        </div>
      </div>

<% end %>

app/views/comments/edit.html.erb
<div class="container">

<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>


</div>

app/views/comments/index.html.erb
 

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th>Link</th>
      <th>Picture</th>
      <th>User</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.text %></td>
        <td><%= comment.link %></td>
        <td><%= comment.picture %></td>
        <td><%= comment.user %></td>
        <td><%= comment.post %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<head>
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <link rel="stylesheet" type="text/css" href="assets/css/bootstrap.css">

   <!-- Website CSS style -->
   <link rel="stylesheet" type="text/css" href="assets/css/main.css">

   <!-- Website Font style -->
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">

   <!-- Google Fonts -->
   <link href='https://fonts.googleapis.com/css?family=Passion+One' rel='stylesheet' type='text/css'>
   <link href='https://fonts.googleapis.com/css?family=Oxygen' rel='stylesheet' type='text/css'>

   <% title "Comment" %>
 </head>

<div class="container">
<h1 class="title">Create Comment</h1>
</div>
<%= render 'form', comment: @comment, post: @post %>

app/views/comments/show.html.erb
<head>
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <link rel="stylesheet" type="text/css" href="assets/css/bootstrap.css">

   <!-- Website CSS style -->
   <link rel="stylesheet" type="text/css" href="assets/css/main.css">

   <!-- Website Font style -->
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">

   <!-- Google Fonts -->
   <link href='https://fonts.googleapis.com/css?family=Passion+One' rel='stylesheet' type='text/css'>
   <link href='https://fonts.googleapis.com/css?family=Oxygen' rel='stylesheet' type='text/css'>

   <% title "Comment" %>
 </head>
<div class="container">
 <div class="row">

          <div class="form-group">
            <h1 class='title'> Comment: </h1>
            <br>
						<a><%= link_to('Posted by: '+' '+User.find(@comment.user_id).name+' '+User.find(@comment.user_id).lastname, '/users/show/'+User.find(@comment.user_id).id.to_s )%></a>
            <br>
            <br>
            <textarea disabled> <%= @comment.text %></textarea>
            <br>
            <br>
            <div class="form-group" align="center">

              <%= image_tag(@comment.image, style:'width:200px')  if @comment.image.attached?%>
            </div>

        <% if current_user.present? %>
        <% if current_user.id == @comment.user_id || current_user.sadmin%>
        <br>
        <br>
        	<a type="Edit" class="btn btn-primary" href="/comments/<%= @comment.id %>/edit">Edit</a>
        <% end %>
        <% end %>

        <a type="Back" class="btn btn-primary" href="/posts/<%= @comment.post_id %>">Back</a>



      </div>
    </div>
  </div>