config/routes.rb
Rails.application.routes.draw do
  #get 'top/index'
  get 'users/index'
  get 'use/' => "term#use"
  get 'service/' => "term#service"
  get 'search/' => "search#index"

  root "posts#index"
  resources :comments
  resources :walls
  resources :posts
  resources :blacklists
  #resources :top
  resources :term

  match '/users',   to: 'users#index',   via: 'get'
  match '/users/show/:id',   to: 'users#show',   via: 'get'
  match '/users/edit/:id',   to: 'users#edit',   via: 'get'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :posts do
    resources :likes
  end
  resources :posts do
    resources :downvotes
  end
  resources :posts do
    resources :inappropriates
  end


  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blacklist.rb
class Blacklist < ApplicationRecord
    has_one :user
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_one_attached :image
end

app/models/downvote.rb
class Downvote < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/inappropriate.rb
class Inappropriate < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comment
  has_many_attached :image
  has_many :likes, dependent: :destroy
  has_many :downvotes, dependent: :destroy
  has_many :inappropriates, dependent: :destroy
  has_one_attached :image

  def self.search(search)
    if search
      where(["title LIKE ?","%#{search}%"])
    else
      all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  devise :omniauthable, omniauth_providers: [:google_oauth2]
  has_many :post
  has_many :comment
  belongs_to :blacklist, optional: true
  has_one_attached :avatar
  


  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first

    # Uncomment the section below if you want users to be created if they don't exist
    unless user
      user = User.create(name: data['first_name'],
         lastname: data['last_name'],
         email: data['email'],
         password: Devise.friendly_token[0,20]
      )
    end
    user
  end
end

app/controllers/term_controller.rb
class TermController < ApplicationController
  def use
  end

  def service
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def google_oauth2
        # You need to implement the method below in your model (e.g. app/models/user.rb)
        @user = User.from_omniauth(request.env['omniauth.auth'])

        if @user.persisted?
          flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
          sign_in_and_redirect @user, event: :authentication
        else
          session['devise.google_data'] = request.env['omniauth.auth'].except(:extra) # Removing extra as it can overflow some session stores
          redirect_to "/"

        end
    end
      

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, :except => [:show]
  def index
  end
  def show
    @user = User.find(params[:id])
  end
  def edit
    @user = User.find(params[:id])
  end
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to adminpanel_path
    else
      render 'edit'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def title(page_title)
        content_for(:title) { page_title }
      end
end

app/helpers/blacklists_helper.rb
module BlacklistsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
      count: resource.errors.count,
      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">x</button>
      <h4>#{sentence}</h4>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/downvotes_helper.rb
module DownvotesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/term_helper.rb
module TermHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/helpers/walls_helper.rb
module WallsHelper
end

app/views/users/_form.html.erb
<style media="screen">
  input[type=text], select {
  width: 100%;
  padding: 12px 30px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
  }

  input[type=email], select {
  width: 100%;
  padding: 12px 30px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
  }

  input[type=password], select {
  width: 100%;
  padding: 12px 30px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
  }

  textarea {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
  }

  input[type=submit] {
  width: 100%;
  margin-top: 0%;
  width: fit-content ;
  position: relative;
  border-color: #ff4900!important;
  background-color: #ffd9b3!important;
  color: #ff4900!important;
  }
</style>

<%= form_for(@user) do |f| %>
  <%= devise_error_messages! %>

  <div class="form-group">
    <div class="row">
      <div class="col-sm-4">
        <% if resource.avatar.attached? %>
     <%= image_tag resource.avatar.variant(resize: "100x100!"),  class: "rounded-circle" %>
    <% else %>
      <%= image_tag gravatar_image_url(current_user.email, size:40), height: 100, width: 100, class: "rounded-circle"%>
    <% end %>
      </div>

      <div class="col-sm-6">
        <%= f.file_field :avatar %>
      </div>
    </div>
  </div>


  <div class="form-group">
    <%= f.text_field :name, autofocus: false, class: 'form-control', placeholder: "Name" %>
  </div>

  <div class="form-group">
    <%= f.text_field :lastname, autofocus: false, class: 'form-control', placeholder: "Lastname" %>
  </div>

  <div class="form-group">
    <%= f.text_area :biography, autofocus: false, class: 'form-control', placeholder: "Biography" %>
  </div>
  <div class="form-group">
    <%= f.text_field :city %>
  </div>
  <div class="form-group">
    <%= f.text_field :country,  class: 'form-control', placeholder: "Country" %>
  </div>

  <div class="form-group">
    <%= f.email_field :email, class: 'form-control', placeholder: 'Email Address' %>
  </div>

  <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
    <div class="alert alert-warning">Currently waiting confirmation for: <%= resource.unconfirmed_email %></div>
  <% end %>

  <div class="form-group">
    <%= f.password_field :password, autocomplete: "off", class: 'form-control', placeholder: 'Password'  %>
    <p class="form-text text-muted"><small>Leave password blank if you don't want to change it</small></p>
  </div>

  <div class="form-group">
    <%= f.password_field :password_confirmation, autocomplete: "off", class: 'form-control', placeholder: 'Confirm Password'  %>
  </div>

  <div class="form-group">
    <%= f.password_field :current_password, autocomplete: "off", class: 'form-control', placeholder: 'Current Password'  %>
    <p class="form-text text-muted"><small>We need your current password to confirm your changes</small></p>
  </div>

  <div class="form-group">
    <%= f.submit "Save Changes", class: 'btn-primary' %>
  </div>
<% end %>
<hr>

<p class="text-center"><%= link_to "Deactivate my account", registration_path(resource_name), data: { confirm: "Are you sure? You cannot undo this." }, method: :delete %></p>
</div>
</div>
</div>

app/views/users/edit.html.erb
<% title "Editar Perfil" %>


<%= render 'form', user: @user %>

app/views/users/index.html.erb
<% @users = User.all %>
<div class="container">
  <center>
  <h1>All Users</h1>
    <br>
<% @users.each do |user| %>
  <h4><%= user.name+' '+user.lastname %></h4>
  <%= link_to user.email,'/users/show/'+user.id.to_s %>
  
  <br>
  <br>
<% end %>
</center>
</div>

app/views/users/show.html.erb
<% title "Profile" %>
<style media="screen">
	input[id="1"] {
  width: 100%;
  margin-top: 0%;
  width: fit-content ;
  position: relative;
  border-color: #ff4900!important;
  background-color: #ffd9b3!important;
  color: #ff4900!important;
  }
</style>

<div class="container">
      <div class="row">
      <div class="col-md-5  toppad  pull-right col-md-offset-3 ">
       <br>
      </div>
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-3 col-lg-offset-3 toppad" >


          <div class="panel panel-info">
            <div class="panel-heading">
              <h3 class="panel-title"><%= @user.name %> <%= @user.lastname %></h3>
            </div>
            <div class="panel-body">
              <div class="row">
                <div class="col-md-3 col-lg-3" align="center" style="width:150">
                   <%= image_tag(@user.avatar, style:'width:100px')  if @user.avatar.attached?%>
                  </div>

                <div class=" col-md-9 col-lg-9 ">
                  <table class="table table-user-information">
                    <tbody>
                      <tr>
                        <td>Biography:</td>
                        <td><%= @user.biography %></td>
                      </tr>

                        <td>Location:</td>
                        <td><%= @user.location %></td>
                      <tr>
                        <td>Country:</td>
                        <td><%= @user.country %></td>
                      </tr>
                      <tr>
                        <tr>
                          <td>City:</td>
                          <td><%= @user.city %></td>
                        </tr>
                        <tr>
                        <td>Email</td>
                        <td><a href="mailto:info@support.com"><%= @user.email %></a></td>
                      </tr>


                    </tbody>
                  </table>

                  <button type="submit" class="btn btn-primary"><%= link_to "Posts","/walls/#{@user.id}", :id => @user.id %></button>

                </div>
              </div>
            </div>


          </div>
      </div>
  </div>
</div>