config/routes.rb
Rails.application.routes.draw do
  #get 'top/index'
  get 'users/index'
  get 'use/' => "term#use"
  get 'service/' => "term#service"
  get 'search/' => "search#index"

  root "posts#index"
  resources :comments
  resources :walls
  resources :posts
  resources :blacklists
  #resources :top
  resources :term

  match '/users',   to: 'users#index',   via: 'get'
  match '/users/show/:id',   to: 'users#show',   via: 'get'
  match '/users/edit/:id',   to: 'users#edit',   via: 'get'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :posts do
    resources :likes
  end
  resources :posts do
    resources :downvotes
  end
  resources :posts do
    resources :inappropriates
  end


  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blacklist.rb
class Blacklist < ApplicationRecord
    has_one :user
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_one_attached :image
end

app/models/downvote.rb
class Downvote < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/inappropriate.rb
class Inappropriate < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comment
  has_many_attached :image
  has_many :likes, dependent: :destroy
  has_many :downvotes, dependent: :destroy
  has_many :inappropriates, dependent: :destroy
  has_one_attached :image

  def self.search(search)
    if search
      where(["title LIKE ?","%#{search}%"])
    else
      all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  devise :omniauthable, omniauth_providers: [:google_oauth2]
  has_many :post
  has_many :comment
  belongs_to :blacklist, optional: true
  has_one_attached :avatar
  


  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first

    # Uncomment the section below if you want users to be created if they don't exist
    unless user
      user = User.create(name: data['first_name'],
         lastname: data['last_name'],
         email: data['email'],
         password: Devise.friendly_token[0,20]
      )
    end
    user
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.search(params[:search])
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description, :location, :country, :city, :state, :user_id, :image)
    end
end

app/controllers/term_controller.rb
class TermController < ApplicationController
  def use
  end

  def service
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def title(page_title)
        content_for(:title) { page_title }
      end
end

app/helpers/blacklists_helper.rb
module BlacklistsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
      count: resource.errors.count,
      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">x</button>
      <h4>#{sentence}</h4>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/downvotes_helper.rb
module DownvotesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/term_helper.rb
module TermHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/helpers/walls_helper.rb
module WallsHelper
end

app/views/posts/edit.html.erb
<head>
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <link rel="stylesheet" type="text/css" href="assets/css/bootstrap.css">

   <!-- Website CSS style -->
   <link rel="stylesheet" type="text/css" href="assets/css/main.css">

   <!-- Website Font style -->
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">

   <!-- Google Fonts -->
   <link href='https://fonts.googleapis.com/css?family=Passion+One' rel='stylesheet' type='text/css'>
   <link href='https://fonts.googleapis.com/css?family=Oxygen' rel='stylesheet' type='text/css'>

   <% title "Posts" %>
 </head>
<h1 class="title">Editing Post</h1>

<%= render 'form', post: @post %>

app/views/posts/index.html.erb
 <head>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" type="text/css" href="assets/css/bootstrap.css">

		<!-- Website CSS style -->
		<link rel="stylesheet" type="text/css" href="assets/css/main.css">

		<!-- Website Font style -->
	    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">

		<!-- Google Fonts -->
		<link href='https://fonts.googleapis.com/css?family=Passion+One' rel='stylesheet' type='text/css'>
		<link href='https://fonts.googleapis.com/css?family=Oxygen' rel='stylesheet' type='text/css'>

    <% title "Posts" %>
	</head>
<h1 class= "title">Most recent posts</h1>
<hr/>
      <% @posts.each do |post| %>
          <div class="col-md-6">
        <div class="well well-sm">
            <div class="row">
                <div class="col-xs-3 col-md-3 text-center">
                  <%if post.image.attached?%>
                  <%= image_tag(post.image, style:'width:100px') %>
                  <% else %>
                  <img class="img-responsive user-photo" src="http://cdn.onlinewebfonts.com/svg/img_237724.png" style= 'width:100px'>
                  <% end %>

                </div>
                <div class="col-xs-9 col-md-9 section-box">
                        <a  href="/posts/<%= post.id %>" > <h2><%= post.title%></h2> </a>
                        <p><%= post.description%></p>
                    <hr />
                    <div class="row rating-desc">
                        <div class="col-md-12">

                            <span class="glyphicon glyphicon-heart"></span>  <%= post.likes.count %> <%= (post.likes.count) == 1 ? 'Upvote' : 'Upvotes'%>	<%= post.downvotes.count %> <%= (post.downvotes.count) == 1 ? 'Downvote' : 'Downvotes'%><span class="separator">|</span>
                            <span class="glyphicon glyphicon-comment"></span>  (<%= post.comment.count %> <%= (post.comment.count) == 1 ? 'Comment' : 'Comments'%>)
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/posts/new.html.erb
<head>
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <link rel="stylesheet" type="text/css" href="assets/css/bootstrap.css">

   <!-- Website CSS style -->
   <link rel="stylesheet" type="text/css" href="assets/css/main.css">

   <!-- Website Font style -->
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">

   <!-- Google Fonts -->
   <link href='https://fonts.googleapis.com/css?family=Passion+One' rel='stylesheet' type='text/css'>
   <link href='https://fonts.googleapis.com/css?family=Oxygen' rel='stylesheet' type='text/css'>

   <% title "Comment" %>
 </head>
<div class="container">
<h1 class="title">Create post</h1>
</div>

<%= render 'form', post: @post%>

app/views/posts/show.html.erb
<head>
	 <meta name="viewport" content="width=device-width, initial-scale=1">
	 <link rel="stylesheet" type="text/css" href="assets/css/bootstrap.css">

	 <!-- Website CSS style -->
	 <link rel="stylesheet" type="text/css" href="assets/css/main.css">

	 <!-- Website Font style -->
		 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">

	 <!-- Google Fonts -->
	 <link href='https://fonts.googleapis.com/css?family=Passion+One' rel='stylesheet' type='text/css'>
	 <link href='https://fonts.googleapis.com/css?family=Oxygen' rel='stylesheet' type='text/css'>

	 <% title "Post" %>
 </head>
<style media="screen">
	input[type=submit] {
  width: 100%;
  margin-top: 0%;
  width: fit-content ;
  position: relative;
  border-color: #ff4900!important;
  background-color: #ffd9b3!important;
  color: #ff4900!important;
  }
	.grid-container {
	  display: grid;
	  grid-template-columns: auto auto auto auto;
	  grid-gap: 10px;
	  background-color: #2196F3;
	  padding: 10px;
	}

	.grid-container > div {
	  background-color: rgba(255, 255, 255, 0.8);
	  text-align: center;
	  padding: 20px 0;
	  font-size: 30px;
	}

</style>

<div class="container">
	<h1 class= "title">Post</h1>
	<hr/>
	<div class="row">



	    <div class="col-md-8 col-md-offset-0">
        <div class="post_area">

    		<form action="" method="POST" >

						<div class="form-group">
							<br>
							<% if @post.user_id.present? %>
								<a><%= link_to('Posted by: '+' '+User.find(@post.user_id).name+' '+User.find(@post.user_id).lastname, '/users/show/'+User.find(@post.user_id).id.to_s )%></a>
							<% end %>
						</div>

						<div class="form-group">
								<label for="title">Title: <span class="require"><%= @post.title %></span></label>
						</div>

						<div class="form-group">
								<label for="date">Creation Date: <span class="require"><%= @post.created_at %></span></label>
						</div>

    		    <div class="form-group">
    		        <label for="location">Location: <span class="require"><%= @post.location %></span></label>
    		    </div>

            <div class="form-group">
    		        <label for="country">Country: <span class="require"><%= @post.country %></span></label>
    		    </div>

            <div class="form-group">
    		        <label for="city">City: <span class="require"><%= @post.city %></span></label>
    		    </div>

    		    <div class="form-group" >
    		        <label for="description">Description: </label>
                <div class="post_text">
                  <%= @post.description %>
                </div>
								<div class="form-group">


								</div>
    		    </div>
							<div class="form-group" align="center">
							<%= image_tag(@post.image, style:'width:200px')  if @post.image.attached?%>
							</div>
    		</form>
        </div>

        <div class="container">
					<div class="col-sm-12">
						<div class="col-2">
							<br>
						<% if current_user.present? %>
						<% if current_user.id == @post.user_id || current_user.sadmin %>
							<a type="submit" class="btn btn-primary" href="/posts/<%= @post.id %>/edit">Edit</a>
						<% end %>
						<% end %>
						</div>
						<h2>Comments</h2>

						<div class="container-grid">
						<% if user_signed_in? %>
						<h4><%= @post.likes.count %> <%= (@post.likes.count) == 1 ? 'Upvote' : 'Upvotes'%>	<%= @post.downvotes.count %> <%= (@post.downvotes.count) == 1 ? 'Downvote' : 'Downvotes'%>	<%= @post.inappropriates.count %> <%= (@post.inappropriates.count) == 1 ? 'Inappropriate' : 'Inappropriates'%></h4>
						<%= link_to "Add Comment", new_comment_path(post_id: @post.id) %>
						<div>
						<br>
						</div>



							<div class="col-sm-1 ">
						<% pre_like = @post.likes.find { |like| like.user_id == current_user.id} %>
						<% if pre_like %>
						  <%= button_to 'Upvote', post_like_path(@post, pre_like), method: :delete %>
						<% else %>
						  <%= button_to 'Upvote', post_likes_path(@post), method: :post %>
						<% end %>
						</div>

						<div class="col-sm-1">
						<% pre_downvote = @post.downvotes.find { |downvote| downvote.user_id == current_user.id} %>
						<% if pre_downvote %>
						  <%= button_to 'Downvote', post_downvote_path(@post, pre_downvote), method: :delete %>
						<% else %>
						  <%= button_to 'Downvote', post_downvotes_path(@post), method: :post %>
						<% end %>
						</div>
						<% end %>
						</div>

					</div>



					<% @post.comment.each do |c| %>


          <div class="row">
            <!-- /col-sm-12 -->
          </div><!-- /row -->
          <div class="row">
						<div class="row comnts">

				          </div>

				      </div>
            <div class="col-sm-1">
              <div class="thumbnail">
								<%if c.user.avatar.attached? %>
								<%= image_tag(c.user.avatar, style:'width:100px')  %>
								<% else %>
                <img class="img-responsive user-photo" src="http://www.31minutos.cl/wp-content/uploads/2014/02/thumb-bodoque-300x300.jpg">
								<% end %>
							</div><!-- /thumbnail -->
            </div><!-- /col-sm-1 -->

            <div class="col-sm-5">
              <div class="panel panel-default">
                <div class="panel-heading">
                  <strong><%= c.user.name+' '+c.user.lastname %></strong> <span class="text-muted"><%= time_ago_in_words(c.created_at) %></span>
                </div>
                  <div class="panel-body">
                  <%=c.text%>
									<br>
									<br>
									<%= link_to "Show Comment", comment_path(c) %>
                </div><!-- /panel-body -->
              </div><!-- /panel panel-default -->
            </div><!-- /col-sm-5 -->
						<% end %>
          </div><!-- /container -->
          </div>



		<div class="col-md-4 col-md-offset-0">
      <div class="related_area">



  			<form action="" method="POST">

            <div class="form-group">
              <h1>Related Post</h1>
            </div>

  					<div class="form-group">

  							<figure class="img-responsive">

  	            	<img src="https://www.mallsyoutletsvivo.cl/vivo-imperio/wp-content/uploads/sites/4/2018/07/logo-Movistar.jpg" width= 150px height=150px>

  							</figure>
  					</div>

  					<div class="form-group">
  							<figure class="img-responsive">
  	            	<img src="https://images-na.ssl-images-amazon.com/images/I/51ZqPur7%2BLL._SX466_.jpg" width= 150px height= 150px>

  							</figure>
  					</div>

  					<div class="form-group">
  							<figure class="img-responsive">
  	            	<img src="https://www2.jumbo.cl/uploads/2019/04/logoJumbo.jpeg" width="87%" height="87%">

  							</figure>
  					</div>

  			</form>
	     </div>
			 <br>
			 <div class="col-sm-2">
				<% if user_signed_in? %>
			 <% pre_inappropriate = @post.inappropriates.find { |inappropriate| inappropriate.user_id == current_user.id} %>
			 <% if pre_inappropriate %>
			 	<%= button_to 'Inappropriate', post_inappropriate_path(@post, pre_inappropriate), method: :delete %>
			 <% else %>
			 	<%= button_to 'Inappropriate', post_inappropriates_path(@post), method: :post %>
			 <% end %>
			 <% end %>
			 </div>


	</div>
</div>


</div>